server:
  port: 8001
  error:
    include-message: always

spring:
  config:
    import:
      - core-db.yml


logging:
  level:
    root: INFO
    com.ticketing: DEBUG
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG

---
spring:
  profiles:
    active: docker
#  data:
#    mongodb:
#      host: mongodb

server.port: 8080