server:
  port: 8001
  error:
    include-message: always

spring:
  config:
    import:
      - mongo-db.yml


logging:
  level:
    root: INFO
    com:
      performance: DEBUG

---
spring:
  profiles:
    active: docker
#  data:
#    mongodb:
#      host: mongodb

server.port: 8080