server:
  port: 8000
  error:
    include-message: always

app:
  performance-service:
    host: localhost
    port: 8001
  hall-service:
    host: localhost
    port: 8002

logging:
  level:
    root: INFO
    com.performance: DEBUG

---
spring:
  profiles:
    active: docker

server.port: 8080

app:
  performance-service:
    host: performance
    port: 8080
  hall-service:
    host: hall
    port: 8080