spring:
  jpa:
    hibernate:
      ddl-auto: update

logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

storage:
  datasource:
    core:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/reservation-db
      username: user
      password: pwd
      data-source-properties:
        rewriteBatchedStatements: true

---
spring.config.activate.on-profile: docker

storage:
  datasource:
    core:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://mysql/reservation-db
      username: user
      password: pwd
      initializationFailTimeout: 60000
      connection-timeout: 60000
      data-source-properties:
        rewriteBatchedStatements: true

---
spring.config.activate.on-profile: test

storage:
  datasource:
    core:
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:mem:core;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      username: sa
      pool-name: core-db-pool
      data-source-properties:
        rewriteBatchedStatements: true

