storage:
  datasource:
    core:
      host: localhost
      port: 27017
      database: performance-db

---
spring.config.activate.on-profile: docker

storage:
  datasource:
    core:
      host: mongodb
      port: 27017
      database: performance-db
      options:
        connectTimeoutMS: 3000        # 연결 시도 타임아웃 (ms)
        socketTimeoutMS: 5000         # 응답 대기 시간 타임아웃 (ms)
        serverSelectionTimeoutMS: 10000  # 서버 선택 시 최대 대기 시간 (ms)
        maxConnectionIdleTimeMS: 10000   # 유휴 연결 제거 시간
        retryWrites: true             # 쓰기 재시도 허용
        retryReads: true              # 읽기 재시도 허용

---

spring:
  config:
    activate:
      on-profile: test

storage:
  datasource:
    core:
      host: localhost
      port: 1
      database: test-db