server:
  port: 8002
  error:
    include-message: always
spring:
  config:
    import:
      - mysql-db.yml

logging:
  level:
    root: INFO
    com.performance: DEBUG

---
spring:
  profiles:
    active: docker
#  datasource:
#    url: jdbc:mysql://mysql/hall-db

server.port: 8080
