server:
  port: 8003
  error:
    include-message: always
spring:
  config:
    import:
      - reservation-db.yml

logging:
  level:
    root: INFO
    com.ticketing: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
---
spring:
  profiles:
    active: docker
#  datasource:
#    url: jdbc:mysql://mysql/hall-db

server.port: 8080
