storage:
  datasource:
    core:
      host: localhost
      port: 27017
      database: performance-db
logging:
  level:
    root: INFO
    com:
      performance: DEBUG
      org.hibernate.SQL: DEBUG


---
spring.config.activate.on-profile: docker

storage:
  datasource:
    core:
      host: mongodb
      port: 27017
      database: performance-db

---

spring:
  config:
    activate:
      on-profile: test

storage:
  datasource:
    core:
      host: localhost
      port: 1
      database: test-db