server:
  port: 8002
  error:
    include-message: always

spring:
  datasource:
    url: jdbc:mysql://localhost/hall-db
    username: user
    password: pwd
    hikari:
      initialization-fail-timeout: 60000

  jpa:
    hibernate:
      ddl-auto: update

logging:
  level:
    root: INFO
    com.performance: DEBUG

---
spring:
  profiles:
    active: docker
#  datasource:
#    url: jdbc:mysql://mysql/hall-db

server.port: 8080
