server:
  port: 8001
  error:
    include-message: always

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: performance-db
      auto-index-creation: true


logging:
  level:
    root: INFO
    com:
      performance: DEBUG

---
spring:
  profiles:
    active: docker
#  data:
#    mongodb:
#      host: mongodb

server.port: 8080